openapi: 3.0.0
info:
  version: 'v1'
  title: 'Movies and Shows API'
servers:
  - url: 'https://d40e0072-3ab3-4306-aa16-ac32bbf2f644.mock.pstmn.io'
paths:
  /movies:
    get:
      summary: 'GetAllMovies'
      operationId: listMovies
      tags:
        - Movies 
      responses:
        '200':
          description: 'List of Movies'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movies'
  /shows:
    get:
      summary: 'GetAllShows'
      operationId: listShows
      tags:
        - Shows 
      responses:
        '200':
          description: 'List of Shows'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shows'
components:
  schemas:
    Movies:
        type: array
        items:
            $ref: "#/components/schemas/Movie"
    Movie:
      type: object
      required:
        - id
        - name
        - certification
        - release_date
        - cast
        - genre
        - languages_available
        - services_available
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        certification:
          type: string
        release_date:
            type: string
        cast:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
                    id:
                        type: integer
                        format: int64  
        genre:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
                    id:
                        type: integer
                        format: int64   
        languages_available:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
        services_available:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string  
    
    Shows:
        type: array
        items:
            $ref: "#/components/schemas/Show"
    Show:
      type: object
      required:
        - id
        - name
        - certification
        - pilot_air_date
        - num_of_seasons
        - cast
        - genre
        - languages_available
        - services_available
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        certification:
          type: string
        pilot_air_date:
            type: string
        num_of_seasons:
            type: integer
            format: int64
        cast:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
                    id:
                        type: integer
                        format: int64  
        genre:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
                    id:
                        type: integer
                        format: int64   
        languages_available:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
        services_available:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string          
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []